<script lang="ts">
  // A chart sheet: its one chart drawn to fill the window, as Excel shows it.
  import type { Worksheet } from '@office-kit/xlsx/worksheet';
  import { chartData } from '../core/chart-data.ts';
  import { getEditor } from '../core/context.ts';
  import { renderChartSvg } from '../grid/chart-render.ts';
  import { t } from '../i18n/i18n.svelte.ts';

  let { index }: { index: number } = $props();

  const ctl = getEditor();
  const doc = ctl.doc;
  let width = $state(0);
  let height = $state(0);

  const worksheets = $derived.by(() => {
    void doc.version;
    const map = new Map<string, Worksheet>();
    for (const s of doc.wb.sheets) if (s.kind === 'worksheet') map.set(s.sheet.title, s.sheet);
    return map;
  });

  const svg = $derived.by(() => {
    void doc.version;
    const ref = doc.wb.sheets[index];
    if (ref?.kind !== 'chartsheet' || width === 0 || height === 0) return undefined;
    const item = ref.sheet.drawing?.items.find((i) => i.content.kind === 'chart');
    if (item?.content.kind !== 'chart') return undefined;
    const data = chartData(item.content.chart, doc.calc, worksheets, doc.styles.palette);
    // Excel keeps a margin of white around the chart on screen.
    return data ? renderChartSvg(data, Math.max(40, width - 32), Math.max(30, height - 32), doc.styles.palette) : undefined;
  });
</script>

<div class="chartsheet" bind:clientWidth={width} bind:clientHeight={height} role="img" aria-label={doc.wb.sheets[index]?.sheet.title}>
  {#if svg}
    <!-- The SVG is generated by renderChartSvg from chart data, with text escaped there. -->
    <div class="chart">{@html svg}</div>
  {:else if width > 0}
    <p class="empty">{t('chartsheetUnsupported')}</p>
  {/if}
</div>

<style>
  .chartsheet {
    position: relative;
    width: 100%;
    height: 100%;
    background: #fff;
    overflow: hidden;
  }
  .chart {
    position: absolute;
    inset: 16px;
  }
  .empty {
    margin: 40px;
    color: #666;
  }
</style>
